services:
  db:
    image: postgres:14
    container_name: password_manager_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: password_manager_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/password_manager
      SECRET_KEY: your_secret_key
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

volumes:
  postgres_data:
